// Generated by tools/generate_gpu_production_material_shader.py
// production_water_source_sha256=866e95075cbc106b15efbf17f9571627c847187eed2539282d4dcfc3f1447c4d

#[vertex]
#version 450

#define MAX_VIEWS 2

struct WtSceneDataMatrices {
	mat4 projection_matrix;
	mat4 inv_projection_matrix;
	mat3x4 inv_view_matrix;
	mat3x4 view_matrix;
#ifdef USE_DOUBLE_PRECISION
	vec4 inv_view_precision;
#endif
	mat4 projection_matrix_view[MAX_VIEWS];
};

layout(set = 0, binding = 0, std140) uniform SceneDataBlock {
	WtSceneDataMatrices data;
} scene_data_block;

layout(location = 0) in vec3 vertex_position;
layout(location = 1) in vec2 vertex_normal;

layout(push_constant, std430) uniform Params {
	ivec4 view;
	ivec4 viewport;
	vec4 quantization_min;
	vec4 quantization_extent;
} params;

layout(location = 0) out vec3 world_normal;
layout(location = 1) out vec3 world_view_direction;
layout(location = 2) out vec3 view_normal;

void main() {
	mat4 view_matrix = transpose(mat4(
		scene_data_block.data.view_matrix[0],
		scene_data_block.data.view_matrix[1],
		scene_data_block.data.view_matrix[2],
		vec4(0.0, 0.0, 0.0, 1.0)
	));
	mat4 projection = scene_data_block.data.projection_matrix;
	if (params.view.y > 1) {
		projection = scene_data_block.data.projection_matrix_view[params.view.x];
	}
	vec3 world_position = vertex_position;
	vec3 view_position = (view_matrix * vec4(world_position, 1.0)).xyz;
	vec2 octahedral = vertex_normal;
	vec3 decoded_normal = vec3(
		octahedral,
		1.0 - abs(octahedral.x) - abs(octahedral.y)
	);
	if (decoded_normal.z < 0.0) {
		decoded_normal.xy = (1.0 - abs(decoded_normal.yx)) *
			sign(decoded_normal.xy);
	}
	world_normal = normalize(decoded_normal);
	view_normal = normalize(mat3(view_matrix) * world_normal);
	world_view_direction = normalize(
		transpose(mat3(view_matrix)) * -view_position
	);
	gl_Position = projection * vec4(view_position, 1.0);
}

#[fragment]
#version 450

layout(location = 0) in vec3 world_normal;
layout(location = 1) in vec3 world_view_direction;
layout(location = 2) in vec3 view_normal;
layout(location = 0) out vec4 output_color;

layout(push_constant, std430) uniform Params {
	ivec4 view;
	ivec4 viewport;
	vec4 quantization_min;
	vec4 quantization_extent;
} params;

layout(set = 1, binding = 0, std140) uniform ProductionWaterParams {
	vec4 deep_color;
	vec4 edge_color;
	vec4 response;
} water_params;

layout(set = 2, binding = 0) uniform sampler2D opaque_scene;

void main() {
	float signed_facing = dot(
		normalize(world_normal), normalize(world_view_direction)
	);
	float facing = abs(signed_facing);
	float fresnel = pow(1.0 - facing, 5.0);
	vec3 tint = mix(water_params.deep_color.rgb, water_params.edge_color.rgb, fresnel);
	float tint_strength = mix(
		water_params.response.x, water_params.response.y, fresnel
	);
	if (signed_facing < 0.0) {
		tint = water_params.deep_color.rgb;
		tint_strength = max(tint_strength, 0.58);
	}
	vec2 screen_uv = gl_FragCoord.xy / vec2(params.viewport.xy);
	vec2 offset = view_normal.xy * water_params.response.z * (0.35 + 0.65 * fresnel);
	vec2 sample_uv = clamp(screen_uv + offset, vec2(0.001), vec2(0.999));
	vec3 background = textureLod(opaque_scene, sample_uv, 0.0).rgb;
	output_color = vec4(mix(background, tint, tint_strength), 1.0);
}
