// Generated by tools/generate_gpu_production_material_shader.py
// production_water_source_sha256=866e95075cbc106b15efbf17f9571627c847187eed2539282d4dcfc3f1447c4d

#[vertex]
#version 450

#define MAX_VIEWS 2

struct WtSceneDataMatrices {
	mat4 projection_matrix;
	mat4 inv_projection_matrix;
	mat3x4 inv_view_matrix;
	mat3x4 view_matrix;
#ifdef USE_DOUBLE_PRECISION
	vec4 inv_view_precision;
#endif
	mat4 projection_matrix_view[MAX_VIEWS];
};

layout(set = 0, binding = 0, std140) uniform SceneDataBlock {
	WtSceneDataMatrices data;
} scene_data_block;

layout(location = 0) in vec4 vertex_position;
layout(location = 1) in vec4 vertex_normal;

layout(push_constant, std430) uniform Params {
	ivec4 view;
} params;

layout(location = 0) out vec3 world_normal;
layout(location = 1) out vec3 world_view_direction;

void main() {
	mat4 view_matrix = transpose(mat4(
		scene_data_block.data.view_matrix[0],
		scene_data_block.data.view_matrix[1],
		scene_data_block.data.view_matrix[2],
		vec4(0.0, 0.0, 0.0, 1.0)
	));
	mat4 projection = scene_data_block.data.projection_matrix;
	if (params.view.y > 1) {
		projection = scene_data_block.data.projection_matrix_view[params.view.x];
	}
	vec3 view_position = (view_matrix * vec4(vertex_position.xyz, 1.0)).xyz;
	world_normal = normalize(vertex_normal.xyz);
	world_view_direction = normalize(
		transpose(mat3(view_matrix)) * -view_position
	);
	gl_Position = projection * vec4(view_position, 1.0);
}

#[fragment]
#version 450

layout(location = 0) in vec3 world_normal;
layout(location = 1) in vec3 world_view_direction;
layout(location = 0) out vec4 output_color;

layout(set = 1, binding = 0, std140) uniform ProductionWaterParams {
	vec4 deep_color;
	vec4 edge_color;
	vec4 response;
} water_params;

void main() {
	float facing = abs(dot(
		normalize(world_normal), normalize(world_view_direction)
	));
	float fresnel = pow(1.0 - facing, 5.0);
	vec3 tint = mix(water_params.deep_color.rgb, water_params.edge_color.rgb, fresnel);
	float tint_strength = mix(
		water_params.response.x, water_params.response.y, fresnel
	);
	if (!gl_FrontFacing) {
		tint = water_params.deep_color.rgb;
		tint_strength = max(tint_strength, 0.58);
	}
	// Standard alpha blending reproduces mix(background, tint, tint_strength).
	// Screen-space refraction remains an explicit unsupported response.
	output_color = vec4(tint, tint_strength);
}
