// Generated by tools/generate_gpu_production_material_shader.py
// production_material_source_sha256=dfe69187f369fe01dc207c40cd52ac6d32e29e4ce7c2d4f21f9e6c221f08d35a

#[vertex]
#version 450

#define MAX_VIEWS 2

struct WtSceneDataMatrices {
	mat4 projection_matrix;
	mat4 inv_projection_matrix;
	mat3x4 inv_view_matrix;
	mat3x4 view_matrix;
#ifdef USE_DOUBLE_PRECISION
	vec4 inv_view_precision;
#endif
	mat4 projection_matrix_view[MAX_VIEWS];
};

layout(set = 0, binding = 0, std140) uniform SceneDataBlock {
	WtSceneDataMatrices data;
} scene_data_block;

layout(location = 0) in vec4 vertex_position;
layout(location = 1) in vec4 vertex_normal;
layout(location = 2) in ivec4 vertex_meta;

layout(push_constant, std430) uniform Params {
	ivec4 view;
} params;

layout(location = 0) out vec3 world_position;
layout(location = 1) out vec3 world_normal;
layout(location = 2) out vec4 generated_material_weights_low;
layout(location = 3) out vec4 generated_material_weights_high;
layout(location = 4) out vec4 authored_material_weights_low;
layout(location = 5) out vec4 authored_material_weights_high;

int material_weight_slot(int material) {
	if (material == 1) return 0;
	if (material == 2) return 1;
	if (material == 3) return 2;
	if (material == 4) return 3;
	if (material == 5) return 4;
	if (material == 7) return 5;
	if (material == 8) return 6;
	if (material == 10) return 7;
	return -1;
}

void main() {
	mat4 view_matrix = transpose(mat4(
		scene_data_block.data.view_matrix[0],
		scene_data_block.data.view_matrix[1],
		scene_data_block.data.view_matrix[2],
		vec4(0.0, 0.0, 0.0, 1.0)
	));
	mat4 projection = scene_data_block.data.projection_matrix;
	if (params.view.y > 1) {
		projection = scene_data_block.data.projection_matrix_view[params.view.x];
	}
	world_position = vertex_position.xyz;
	world_normal = normalize(vertex_normal.xyz);
	gl_Position = projection * view_matrix * vec4(world_position, 1.0);
	generated_material_weights_low = vec4(0.0);
	generated_material_weights_high = vec4(0.0);
	authored_material_weights_low = vec4(0.0);
	authored_material_weights_high = vec4(0.0);
	int slot = material_weight_slot(vertex_meta.x);
	if (slot < 0) {
		return;
	}
	if (vertex_meta.y != 0) {
		if (slot < 4) authored_material_weights_low[slot] = 1.0;
		else authored_material_weights_high[slot - 4] = 1.0;
	} else {
		if (slot < 4) generated_material_weights_low[slot] = 1.0;
		else generated_material_weights_high[slot - 4] = 1.0;
	}
}

#[fragment]
#version 450

layout(location = 0) in vec3 world_position;
layout(location = 1) in vec3 world_normal;
layout(location = 2) in vec4 generated_material_weights_low;
layout(location = 3) in vec4 generated_material_weights_high;
layout(location = 4) in vec4 authored_material_weights_low;
layout(location = 5) in vec4 authored_material_weights_high;
layout(location = 0) out vec4 output_color;

layout(set = 1, binding = 0, std140) uniform ProductionMaterialParams {
	vec4 feature_flags;
	vec4 scalar_0;
	vec4 scalar_1;
	vec4 scalar_2;
	vec4 world_size;
	vec4 road_grades[18];
} material_params;
layout(set = 1, binding = 1) uniform sampler2D checker_texture;
layout(set = 1, binding = 2) uniform sampler2DArray terrain_albedo_array;
layout(set = 1, binding = 3) uniform sampler2DArray terrain_normal_array;
layout(set = 1, binding = 4) uniform sampler2DArray terrain_roughness_array;
layout(set = 1, binding = 5) uniform sampler2D clean_albedo_texture;

#define procedural_ore_worldspace_blend_enabled (material_params.feature_flags.x > 0.5)
#define procedural_rolling_exterior_surface_enabled (material_params.feature_flags.y > 0.5)
#define procedural_road_worldspace_blend_enabled (material_params.feature_flags.z > 0.5)
#define procedural_four_biome_world_enabled (material_params.feature_flags.w > 0.5)
#define procedural_seed_phase material_params.scalar_0.x
#define procedural_ore_blend_width material_params.scalar_0.y
#define procedural_road_half_width material_params.scalar_0.z
#define procedural_road_shoulder_width material_params.scalar_0.w
#define procedural_surface_cover_full_depth material_params.scalar_1.x
#define procedural_surface_cover_fade_depth material_params.scalar_1.y
#define procedural_surface_cover_normal_start material_params.scalar_1.z
#define procedural_surface_cover_normal_end material_params.scalar_1.w
#define procedural_surface_biome_height_blend_width material_params.scalar_2.x
#define procedural_surface_biome_noise_blend_width material_params.scalar_2.y
#define procedural_world_size_xz material_params.world_size.xy
#define procedural_road_grade_0 material_params.road_grades[0].xy
#define procedural_road_grade_1 material_params.road_grades[1].xy
#define procedural_road_grade_2 material_params.road_grades[2].xy
#define procedural_road_grade_3 material_params.road_grades[3].xy
#define procedural_road_grade_4 material_params.road_grades[4].xy
#define procedural_road_grade_5 material_params.road_grades[5].xy
#define procedural_road_grade_6 material_params.road_grades[6].xy
#define procedural_road_grade_7 material_params.road_grades[7].xy
#define procedural_road_grade_8 material_params.road_grades[8].xy
#define procedural_road_grade_9 material_params.road_grades[9].xy
#define procedural_road_grade_10 material_params.road_grades[10].xy
#define procedural_road_grade_11 material_params.road_grades[11].xy
#define procedural_road_grade_12 material_params.road_grades[12].xy
#define procedural_road_grade_13 material_params.road_grades[13].xy
#define procedural_road_grade_14 material_params.road_grades[14].xy
#define procedural_road_grade_15 material_params.road_grades[15].xy
#define procedural_road_grade_16 material_params.road_grades[16].xy
#define procedural_road_grade_17 material_params.road_grades[17].xy

const vec4 material_1_color = vec4(0.24, 0.25, 0.24, 1.0);
const vec4 material_2_color = vec4(0.28, 0.39, 0.20, 1.0);
const vec4 material_3_color = vec4(0.36, 0.35, 0.33, 1.0);
const vec4 material_4_color = vec4(0.56, 0.49, 0.35, 1.0);
const vec4 material_5_color = vec4(0.68, 0.70, 0.66, 1.0);
const vec4 material_7_color = vec4(0.31, 0.32, 0.31, 1.0);
const vec4 material_8_color = vec4(0.48, 0.29, 0.13, 1.0);
const vec4 material_10_color = vec4(0.09, 0.10, 0.11, 1.0);
const bool clean_visual_enabled = false;
const bool clean_texture_enabled = false;
const vec4 clean_albedo_color = vec4(0.72, 0.65, 0.50, 1.0);
const float clean_texture_world_scale = 0.125;
const bool clean_triplanar_enabled = true;
const float clean_triplanar_blend_sharpness = 4.0;
const bool clean_material_variation_enabled = false;
const float clean_material_variation_strength = 0.08;
const float clean_roughness = 1.0;
const float clean_specular = 0.0;
const float PRODUCTION_TEXTURE_WORLD_SCALE = 0.125;
const float PRODUCTION_TRIPLANAR_BLEND_SHARPNESS = 4.0;

float material_layer(float material_id) {
	if (material_id > 0.5 && material_id < 1.5) {
		return 0.0;
	} else if (material_id > 1.5 && material_id < 2.5) {
		return 1.0;
	} else if (material_id > 2.5 && material_id < 3.5) {
		return 2.0;
	} else if (material_id > 3.5 && material_id < 4.5) {
		return 3.0;
	} else if (material_id > 4.5 && material_id < 5.5) {
		return 4.0;
	} else if (material_id > 6.5 && material_id < 7.5) {
		return 5.0;
	} else if (material_id > 7.5 && material_id < 8.5) {
		return 6.0;
	} else if (material_id > 9.5 && material_id < 10.5) {
		return 7.0;
	}
	return 0.0;
}

vec3 material_array_uv(float material_id, vec2 plane_pos) {
	return vec3(fract(plane_pos * PRODUCTION_TEXTURE_WORLD_SCALE), material_layer(material_id));
}

vec3 triplanar_weights(vec3 normal, float sharpness) {
	vec3 weights = pow(max(abs(normal), vec3(0.0001)), vec3(max(sharpness, 0.001)));
	return weights / max(weights.x + weights.y + weights.z, 0.0001);
}

vec3 clean_texture_color(vec3 world_pos, vec3 normal) {
	if (!clean_triplanar_enabled) {
		return texture(clean_albedo_texture, world_pos.xz * clean_texture_world_scale).rgb;
	}
	vec3 weights = triplanar_weights(normal, clean_triplanar_blend_sharpness);
	vec3 x_projection = texture(clean_albedo_texture, world_pos.zy * clean_texture_world_scale).rgb;
	vec3 y_projection = texture(clean_albedo_texture, world_pos.xz * clean_texture_world_scale).rgb;
	vec3 z_projection = texture(clean_albedo_texture, world_pos.xy * clean_texture_world_scale).rgb;
	return x_projection * weights.x + y_projection * weights.y + z_projection * weights.z;
}

vec3 production_checker_color(vec3 world_pos, vec3 normal) {
	vec3 weights = triplanar_weights(normal, PRODUCTION_TRIPLANAR_BLEND_SHARPNESS);
	vec3 x_projection = texture(checker_texture, world_pos.zy * PRODUCTION_TEXTURE_WORLD_SCALE).rgb;
	vec3 y_projection = texture(checker_texture, world_pos.xz * PRODUCTION_TEXTURE_WORLD_SCALE).rgb;
	vec3 z_projection = texture(checker_texture, world_pos.xy * PRODUCTION_TEXTURE_WORLD_SCALE).rgb;
	return x_projection * weights.x + y_projection * weights.y + z_projection * weights.z;
}

vec4 production_albedo_color(float material_id, vec3 world_pos, vec3 normal) {
	vec3 weights = triplanar_weights(normal, PRODUCTION_TRIPLANAR_BLEND_SHARPNESS);
	vec4 x_projection = texture(terrain_albedo_array, material_array_uv(material_id, world_pos.zy));
	vec4 y_projection = texture(terrain_albedo_array, material_array_uv(material_id, world_pos.xz));
	vec4 z_projection = texture(terrain_albedo_array, material_array_uv(material_id, world_pos.xy));
	return x_projection * weights.x + y_projection * weights.y + z_projection * weights.z;
}

float deterministic_procedural_wave(vec3 world_pos, float phase) {
	return sin(world_pos.x * 0.031 + phase * 1.73) * 0.47 +
		cos(world_pos.z * 0.027 - phase * 1.19) * 0.38 +
		sin((world_pos.x + world_pos.z) * 0.014 + world_pos.y * 0.041 + phase) * 0.29;
}

float procedural_ore_worldspace_weight(vec3 world_pos) {
	float vein = sin(world_pos.x * 0.073 + procedural_seed_phase) *
		cos(world_pos.y * 0.097 - procedural_seed_phase * 0.7) *
		sin(world_pos.z * 0.061 + procedural_seed_phase * 1.3);
	float pocket = deterministic_procedural_wave(
		world_pos, procedural_seed_phase * 0.37
	);
	float vein_weight = smoothstep(
		0.48 - procedural_ore_blend_width,
		0.48 + procedural_ore_blend_width,
		vein
	);
	float pocket_weight = smoothstep(
		0.08 - procedural_ore_blend_width,
		0.08 + procedural_ore_blend_width,
		pocket
	);
	return clamp(vein_weight * pocket_weight, 0.0, 1.0);
}

vec3 procedural_road_segment_field(
	vec2 point,
	vec4 segment,
	vec2 endpoint_grades
) {
	vec2 start = segment.xy;
	vec2 end = segment.zw;
	vec2 direction = end - start;
	float t = clamp(
		dot(point - start, direction) /
			max(dot(direction, direction), 1.0),
		0.0,
		1.0
	);
	float distance_to_segment = length(point - mix(start, end, t));
	float grade = mix(endpoint_grades.x, endpoint_grades.y, t);
	float grade_weight = 1.0 - smoothstep(
		procedural_road_half_width,
		procedural_road_half_width + procedural_road_shoulder_width,
		distance_to_segment
	);
	return vec3(distance_to_segment, grade, grade_weight);
}

vec4 add_procedural_road_segment(vec4 field, vec3 segment) {
	field.x = min(field.x, segment.x);
	field.y += segment.y * segment.z;
	field.z += segment.z;
	field.w = max(field.w, segment.z);
	return field;
}

vec4 procedural_road_field(vec2 point) {
	vec4 field = vec4(1.0e20, 0.0, 0.0, 0.0);
	if (procedural_four_biome_world_enabled) {
		field = add_procedural_road_segment(field, procedural_road_segment_field(point, vec4(360.0, 360.0, 820.0, 420.0), procedural_road_grade_0));
		field = add_procedural_road_segment(field, procedural_road_segment_field(point, vec4(820.0, 420.0, 1020.0, 360.0), procedural_road_grade_1));
		field = add_procedural_road_segment(field, procedural_road_segment_field(point, vec4(1020.0, 360.0, 1640.0, 380.0), procedural_road_grade_2));
		field = add_procedural_road_segment(field, procedural_road_segment_field(point, vec4(1640.0, 380.0, 1700.0, 900.0), procedural_road_grade_3));
		field = add_procedural_road_segment(field, procedural_road_segment_field(point, vec4(1700.0, 900.0, 1600.0, 1600.0), procedural_road_grade_4));
		field = add_procedural_road_segment(field, procedural_road_segment_field(point, vec4(1600.0, 1600.0, 1020.0, 1700.0), procedural_road_grade_5));
		field = add_procedural_road_segment(field, procedural_road_segment_field(point, vec4(1020.0, 1700.0, 400.0, 1600.0), procedural_road_grade_6));
		field = add_procedural_road_segment(field, procedural_road_segment_field(point, vec4(400.0, 1600.0, 300.0, 1100.0), procedural_road_grade_7));
		field = add_procedural_road_segment(field, procedural_road_segment_field(point, vec4(300.0, 1100.0, 400.0, 850.0), procedural_road_grade_8));
		field = add_procedural_road_segment(field, procedural_road_segment_field(point, vec4(400.0, 850.0, 360.0, 360.0), procedural_road_grade_9));
		field = add_procedural_road_segment(field, procedural_road_segment_field(point, vec4(400.0, 850.0, 760.0, 1040.0), procedural_road_grade_10));
		field = add_procedural_road_segment(field, procedural_road_segment_field(point, vec4(760.0, 1040.0, 1024.0, 1024.0), procedural_road_grade_11));
		field = add_procedural_road_segment(field, procedural_road_segment_field(point, vec4(1024.0, 1024.0, 1280.0, 1000.0), procedural_road_grade_12));
		field = add_procedural_road_segment(field, procedural_road_segment_field(point, vec4(1280.0, 1000.0, 1700.0, 900.0), procedural_road_grade_13));
		field = add_procedural_road_segment(field, procedural_road_segment_field(point, vec4(1024.0, 1024.0, 1020.0, 1700.0), procedural_road_grade_14));
		field = add_procedural_road_segment(field, procedural_road_segment_field(point, vec4(1024.0, 1024.0, 1020.0, 360.0), procedural_road_grade_15));
		field = add_procedural_road_segment(field, procedural_road_segment_field(point, vec4(760.0, 1040.0, 1020.0, 1700.0), procedural_road_grade_16));
		field = add_procedural_road_segment(field, procedural_road_segment_field(point, vec4(1280.0, 1000.0, 1600.0, 1600.0), procedural_road_grade_17));
		return field;
	}
	field = add_procedural_road_segment(field, procedural_road_segment_field(
		point,
		vec4(720.0, 820.0, 900.0, 820.0),
		procedural_road_grade_0
	));
	field = add_procedural_road_segment(field, procedural_road_segment_field(
		point,
		vec4(900.0, 820.0, 1080.0, 820.0),
		procedural_road_grade_1
	));
	field = add_procedural_road_segment(field, procedural_road_segment_field(
		point,
		vec4(900.0, 680.0, 900.0, 820.0),
		procedural_road_grade_2
	));
	field = add_procedural_road_segment(field, procedural_road_segment_field(
		point,
		vec4(900.0, 820.0, 900.0, 960.0),
		procedural_road_grade_3
	));
	field = add_procedural_road_segment(field, procedural_road_segment_field(
		point,
		vec4(720.0, 820.0, 760.0, 900.0),
		procedural_road_grade_4
	));
	field = add_procedural_road_segment(field, procedural_road_segment_field(
		point,
		vec4(900.0, 960.0, 1040.0, 940.0),
		procedural_road_grade_5
	));
	return field;
}

float procedural_rolling_hills_height(vec2 point) {
	vec2 center = procedural_world_size_xz * 0.5 - vec2(0.5);
	vec2 normalized = (point - center) / max(center, vec2(1.0));
	float phase = procedural_seed_phase;
	float broad =
		7.5 * sin(point.x * 0.0052 + phase * 1.7) +
		5.0 * cos(point.y * 0.0047 - phase * 1.2) +
		3.0 * sin((point.x + point.y) * 0.0034 + phase);
	float rolling =
		4.0 * sin((point.x - point.y) * 0.008 + phase) *
		cos((point.x + point.y) * 0.006 - phase * 0.6);
	float central_mound = 8.0 * exp(-2.7 * (
		pow(normalized.x - 0.03, 2.0) + pow(normalized.y + 0.06, 2.0)
	));
	float shallow_valley = -5.5 * exp(-5.0 * (
		pow(normalized.x + 0.34, 2.0) + pow(normalized.y - 0.22, 2.0)
	));
	float local =
		1.2 * sin(point.x * 0.018 - phase * 0.5) +
		0.9 * cos(point.y * 0.016 + phase * 0.9);
	return 26.0 + broad + rolling + central_mound + shallow_valley + local;
}

float procedural_gaussian_feature(
	vec2 point,
	vec2 center,
	vec2 radius,
	float amplitude
) {
	vec2 delta = (point - center) / radius;
	float distance_squared = dot(delta, delta);
	if (distance_squared >= 16.0) {
		return 0.0;
	}
	return amplitude * exp(-distance_squared);
}

float procedural_lake_depression_feature(
	vec2 point,
	vec2 center,
	vec2 radius,
	float depth
) {
	float q = length((point - center) / radius);
	if (q >= 1.0) {
		return 0.0;
	}
	return depth * (1.0 - smoothstep(0.15, 1.0, q));
}

float procedural_four_biome_height(vec2 point) {
	float phase = procedural_seed_phase;
	float broad =
		8.0 * sin(point.x * 0.0031 + phase * 1.4) +
		6.5 * cos(point.y * 0.0027 - phase * 0.9) +
		4.5 * sin((point.x + point.y) * 0.0017 + phase * 0.6);
	float rolling =
		5.0 * sin((point.x - point.y) * 0.0073 + phase) *
		cos((point.x + point.y) * 0.0058 - phase * 0.4);
	float detail =
		2.2 * sin(point.x * 0.021 + phase * 0.7) *
		cos(point.y * 0.019 - phase) +
		1.4 * sin((point.x + 2.0 * point.y) * 0.034 + phase * 0.2) +
		0.8 * cos((2.0 * point.x - point.y) * 0.047);
	float features =
		procedural_gaussian_feature(point, vec2(1540.0, 1500.0), vec2(230.0, 210.0), 38.0) +
		procedural_gaussian_feature(point, vec2(1760.0, 1320.0), vec2(170.0, 200.0), 28.0) +
		procedural_gaussian_feature(point, vec2(1280.0, 1730.0), vec2(190.0, 150.0), 26.0) +
		procedural_gaussian_feature(point, vec2(470.0, 1510.0), vec2(250.0, 230.0), 22.0) +
		procedural_gaussian_feature(point, vec2(700.0, 1700.0), vec2(210.0, 180.0), 12.0) +
		procedural_gaussian_feature(point, vec2(350.0, 360.0), vec2(280.0, 230.0), 8.0) +
		procedural_gaussian_feature(point, vec2(800.0, 300.0), vec2(240.0, 200.0), 5.0);
	float lake_depression = max(
		procedural_lake_depression_feature(point, vec2(650.0, 700.0), vec2(230.0, 170.0), 34.0),
		max(
			procedural_lake_depression_feature(point, vec2(1400.0, 700.0), vec2(240.0, 170.0), 36.0),
			procedural_lake_depression_feature(point, vec2(650.0, 1370.0), vec2(220.0, 160.0), 38.0)
		)
	);
	return 34.0 + broad + rolling + detail + features - lake_depression;
}

float procedural_surface_height(vec3 world_pos, vec4 road) {
	float base_surface = procedural_four_biome_world_enabled ?
		procedural_four_biome_height(world_pos.xz) :
		procedural_rolling_hills_height(world_pos.xz);
	if (!procedural_road_worldspace_blend_enabled) {
		return base_surface;
	}
	float road_grade = road.z > 0.0 ? road.y / road.z : base_surface;
	return mix(base_surface, road_grade, road.w);
}

float procedural_exterior_surface_coverage(
	vec3 world_pos,
	vec3 surface_normal,
	vec4 road
) {
	float surface = procedural_surface_height(world_pos, road);
	float distance_from_source_surface = abs(surface - world_pos.y);
	float depth_coverage = 1.0 - smoothstep(
		max(procedural_surface_cover_full_depth, 0.0),
		max(procedural_surface_cover_fade_depth,
			procedural_surface_cover_full_depth + 0.001),
		distance_from_source_surface
	);
	float orientation_coverage = smoothstep(
		procedural_surface_cover_normal_start,
		max(procedural_surface_cover_normal_end,
			procedural_surface_cover_normal_start + 0.001),
		surface_normal.y
	);
	return clamp(depth_coverage * orientation_coverage, 0.0, 1.0);
}

vec4 procedural_surface_biome_weights(vec3 world_pos, vec4 road) {
	if (procedural_four_biome_world_enabled) {
		vec2 center = procedural_world_size_xz * 0.5 - vec2(0.5);
		float vertical_boundary = center.x + 110.0 * sin(
			(world_pos.z - center.y) * 0.0024 + procedural_seed_phase * 0.8
		);
		float horizontal_boundary = center.y + 90.0 * cos(
			(world_pos.x - center.x) * 0.0022 - procedural_seed_phase * 0.7
		);
		bool west = world_pos.x < vertical_boundary;
		bool south = world_pos.z < horizontal_boundary;
		if (west && south) return vec4(1.0, 0.0, 0.0, 0.0);
		if (!west && south) return vec4(0.0, 0.0, 1.0, 0.0);
		if (west && !south) return vec4(0.0, 1.0, 0.0, 0.0);
		return vec4(0.0, 0.0, 0.0, 1.0);
	}
	float surface = procedural_surface_height(world_pos, road);
	float phase = procedural_seed_phase;
	float macro =
		sin(world_pos.x * 0.0042 + phase * 1.5) +
		cos(world_pos.z * 0.0037 - phase * 0.8) +
		0.55 * sin((world_pos.x - world_pos.z) * 0.0021 + phase);
	float dry =
		sin((world_pos.x + world_pos.z) * 0.0051 - phase * 0.4) +
		0.42 * cos(world_pos.x * 0.0063 + phase);
	float height_width = max(procedural_surface_biome_height_blend_width, 0.001);
	float noise_width = max(procedural_surface_biome_noise_blend_width, 0.001);
	float sand = max(
		1.0 - smoothstep(10.0 - height_width, 10.0 + height_width, surface),
		smoothstep(0.85 - noise_width, 0.85 + noise_width, dry)
	);
	float snow = max(
		smoothstep(40.0 - height_width, 40.0 + height_width, surface),
		smoothstep(30.0 - height_width, 30.0 + height_width, surface) *
			smoothstep(0.35 - noise_width, 0.35 + noise_width, macro)
	);
	float gravel = max(
		smoothstep(22.0 - height_width, 22.0 + height_width, surface),
		1.0 - smoothstep(-0.70 - noise_width, -0.70 + noise_width, macro)
	);
	gravel *= 1.0 - snow * 0.65;
	sand *= 1.0 - snow * 0.75;
	float grass = max(
		0.12,
		(1.0 - snow) * (1.0 - sand * 0.75) * (1.0 - gravel * 0.55)
	);
	vec4 weights = max(vec4(grass, gravel, sand, snow), vec4(0.0));
	float total = max(weights.x + weights.y + weights.z + weights.w, 0.0001);
	return weights / total;
}

float procedural_road_worldspace_weight(vec3 world_pos, vec4 road) {
	float road_grade = road.z > 0.0 ? road.y / road.z : world_pos.y;
	float horizontal_weight = 1.0 - smoothstep(
		procedural_road_half_width - 0.75,
		procedural_road_half_width + 0.75,
		road.x
	);
	float surface_weight = 1.0 - smoothstep(4.0, 7.0, abs(world_pos.y - road_grade));
	return clamp(horizontal_weight * surface_weight, 0.0, 1.0);
}

vec3 production_normal_color(float material_id, vec3 world_pos, vec3 normal) {
	vec3 weights = triplanar_weights(normal, PRODUCTION_TRIPLANAR_BLEND_SHARPNESS);
	vec3 x_projection = texture(terrain_normal_array, material_array_uv(material_id, world_pos.zy)).rgb;
	vec3 y_projection = texture(terrain_normal_array, material_array_uv(material_id, world_pos.xz)).rgb;
	vec3 z_projection = texture(terrain_normal_array, material_array_uv(material_id, world_pos.xy)).rgb;
	return x_projection * weights.x + y_projection * weights.y + z_projection * weights.z;
}

float production_roughness_value(float material_id, vec3 world_pos, vec3 normal) {
	vec3 weights = triplanar_weights(normal, PRODUCTION_TRIPLANAR_BLEND_SHARPNESS);
	float x_projection = texture(terrain_roughness_array, material_array_uv(material_id, world_pos.zy)).g;
	float y_projection = texture(terrain_roughness_array, material_array_uv(material_id, world_pos.xz)).g;
	float z_projection = texture(terrain_roughness_array, material_array_uv(material_id, world_pos.xy)).g;
	return x_projection * weights.x + y_projection * weights.y + z_projection * weights.z;
}

float production_worldspace_surface_roughness_value(vec4 weights, vec3 world_pos, vec3 normal) {
	return production_roughness_value(2.0, world_pos, normal) * weights.x +
		production_roughness_value(3.0, world_pos, normal) * weights.y +
		production_roughness_value(4.0, world_pos, normal) * weights.z +
		production_roughness_value(5.0, world_pos, normal) * weights.w;
}

vec4 normalized_surface_weights(vec4 weights) {
	vec4 safe_weights = max(weights, vec4(0.0));
	float weight_sum = safe_weights.x + safe_weights.y + safe_weights.z + safe_weights.w;
	if (weight_sum <= 0.0001) {
		return vec4(0.0);
	}
	return safe_weights / weight_sum;
}

float surface_weight_sum(vec4 weights) {
	vec4 safe_weights = max(weights, vec4(0.0));
	return clamp(safe_weights.x + safe_weights.y + safe_weights.z + safe_weights.w, 0.0, 1.0);
}

vec3 production_surface_base_tint(vec4 weights) {
	return material_2_color.rgb * weights.x +
		material_3_color.rgb * weights.y +
		material_4_color.rgb * weights.z +
		material_5_color.rgb * weights.w;
}

vec4 production_surface_albedo_color(vec4 weights, vec3 world_pos, vec3 normal) {
	return production_albedo_color(2.0, world_pos, normal) * weights.x +
		production_albedo_color(3.0, world_pos, normal) * weights.y +
		production_albedo_color(4.0, world_pos, normal) * weights.z +
		production_albedo_color(5.0, world_pos, normal) * weights.w;
}

vec3 production_surface_normal_color(vec4 weights, vec3 world_pos, vec3 normal) {
	return production_normal_color(2.0, world_pos, normal) * weights.x +
		production_normal_color(3.0, world_pos, normal) * weights.y +
		production_normal_color(4.0, world_pos, normal) * weights.z +
		production_normal_color(5.0, world_pos, normal) * weights.w;
}

float production_surface_roughness_value(vec4 weights, vec3 world_pos, vec3 normal) {
	return production_roughness_value(2.0, world_pos, normal) * weights.x +
		production_roughness_value(3.0, world_pos, normal) * weights.y +
		production_roughness_value(4.0, world_pos, normal) * weights.z +
		production_roughness_value(5.0, world_pos, normal) * weights.w;
}

float material_weight_sum(vec4 low_weights, vec4 high_weights) {
	vec4 safe_low = max(low_weights, vec4(0.0));
	vec4 safe_high = max(high_weights, vec4(0.0));
	return safe_low.x + safe_low.y + safe_low.z + safe_low.w +
		safe_high.x + safe_high.y + safe_high.z + safe_high.w;
}

vec4 production_material_albedo_from_weights(
	vec4 low_weights,
	vec4 high_weights,
	vec3 world_pos,
	vec3 surface_normal
) {
	vec4 safe_low = max(low_weights, vec4(0.0));
	vec4 safe_high = max(high_weights, vec4(0.0));
	float total = material_weight_sum(safe_low, safe_high);
	if (total <= 0.0001) {
		return production_albedo_color(1.0, world_pos, surface_normal);
	}
	vec4 albedo = vec4(0.0);
	if (safe_low.x > 0.0001) albedo += production_albedo_color(1.0, world_pos, surface_normal) * safe_low.x;
	if (safe_low.y > 0.0001) albedo += production_albedo_color(2.0, world_pos, surface_normal) * safe_low.y;
	if (safe_low.z > 0.0001) albedo += production_albedo_color(3.0, world_pos, surface_normal) * safe_low.z;
	if (safe_low.w > 0.0001) albedo += production_albedo_color(4.0, world_pos, surface_normal) * safe_low.w;
	if (safe_high.x > 0.0001) albedo += production_albedo_color(5.0, world_pos, surface_normal) * safe_high.x;
	if (safe_high.y > 0.0001) albedo += production_albedo_color(7.0, world_pos, surface_normal) * safe_high.y;
	if (safe_high.z > 0.0001) albedo += production_albedo_color(8.0, world_pos, surface_normal) * safe_high.z;
	if (safe_high.w > 0.0001) albedo += production_albedo_color(10.0, world_pos, surface_normal) * safe_high.w;
	return albedo / total;
}

float production_material_roughness_from_weights(
	vec4 low_weights,
	vec4 high_weights,
	vec3 world_pos,
	vec3 surface_normal
) {
	vec4 safe_low = max(low_weights, vec4(0.0));
	vec4 safe_high = max(high_weights, vec4(0.0));
	float total = material_weight_sum(safe_low, safe_high);
	if (total <= 0.0001) {
		return production_roughness_value(1.0, world_pos, surface_normal);
	}
	float roughness = 0.0;
	if (safe_low.x > 0.0001) roughness += production_roughness_value(1.0, world_pos, surface_normal) * safe_low.x;
	if (safe_low.y > 0.0001) roughness += production_roughness_value(2.0, world_pos, surface_normal) * safe_low.y;
	if (safe_low.z > 0.0001) roughness += production_roughness_value(3.0, world_pos, surface_normal) * safe_low.z;
	if (safe_low.w > 0.0001) roughness += production_roughness_value(4.0, world_pos, surface_normal) * safe_low.w;
	if (safe_high.x > 0.0001) roughness += production_roughness_value(5.0, world_pos, surface_normal) * safe_high.x;
	if (safe_high.y > 0.0001) roughness += production_roughness_value(7.0, world_pos, surface_normal) * safe_high.y;
	if (safe_high.z > 0.0001) roughness += production_roughness_value(8.0, world_pos, surface_normal) * safe_high.z;
	if (safe_high.w > 0.0001) roughness += production_roughness_value(10.0, world_pos, surface_normal) * safe_high.w;
	return roughness / total;
}

vec3 material_clean_tint(float material_id) {
	if (material_id > 0.5 && material_id < 1.5) {
		return vec3(0.40, 0.42, 0.43);
	}
	if (material_id > 1.5 && material_id < 2.5) {
		return vec3(0.48, 0.60, 0.38);
	} else if (material_id > 2.5 && material_id < 3.5) {
		return vec3(0.52, 0.42, 0.30);
	} else if (material_id > 3.5 && material_id < 4.5) {
		return vec3(0.78, 0.68, 0.50);
	} else if (material_id > 4.5 && material_id < 5.5) {
		return vec3(0.84, 0.86, 0.84);
	} else if (material_id > 6.5 && material_id < 7.5) {
		return vec3(0.52, 0.52, 0.49);
	} else if (material_id > 7.5 && material_id < 8.5) {
		return vec3(0.72, 0.47, 0.20);
	} else if (material_id > 9.5 && material_id < 10.5) {
		return vec3(0.13, 0.14, 0.15);
	}
	return vec3(0.52, 0.48, 0.40);
}

vec3 material_clean_tint_from_weights(vec4 low_weights, vec4 high_weights) {
	vec4 safe_low = max(low_weights, vec4(0.0));
	vec4 safe_high = max(high_weights, vec4(0.0));
	float total = material_weight_sum(safe_low, safe_high);
	if (total <= 0.0001) {
		return material_clean_tint(1.0);
	}
	vec3 tint =
		material_clean_tint(1.0) * safe_low.x +
		material_clean_tint(2.0) * safe_low.y +
		material_clean_tint(3.0) * safe_low.z +
		material_clean_tint(4.0) * safe_low.w +
		material_clean_tint(5.0) * safe_high.x +
		material_clean_tint(7.0) * safe_high.y +
		material_clean_tint(8.0) * safe_high.z +
		material_clean_tint(10.0) * safe_high.w;
	return tint / total;
}

vec3 production_fragment_albedo() {
	vec3 output_albedo = vec3(0.0);
	vec4 generated_low = max(generated_material_weights_low, vec4(0.0));
	vec4 generated_high = max(generated_material_weights_high, vec4(0.0));
	vec4 authored_low = max(authored_material_weights_low, vec4(0.0));
	vec4 authored_high = max(authored_material_weights_high, vec4(0.0));
	vec4 total_low = generated_low + authored_low;
	vec4 total_high = generated_high + authored_high;
	if (clean_visual_enabled) {
		vec3 clean_color = clean_albedo_color.rgb;
		if (clean_texture_enabled) {
			clean_color = clamp(clean_texture_color(world_position, normalize(world_normal)) * clean_albedo_color.rgb * 1.15, vec3(0.0), vec3(1.0));
		}
		if (clean_material_variation_enabled) {
			clean_color = mix(
				clean_color,
				material_clean_tint_from_weights(total_low, total_high),
				clamp(clean_material_variation_strength, 0.0, 1.0)
			);
		}
		output_albedo = clean_color;
	} else {
		vec3 surface_normal = normalize(world_normal);
		float generated_coverage = material_weight_sum(generated_low, generated_high);
		float authored_coverage = material_weight_sum(authored_low, authored_high);
		float total_coverage = max(generated_coverage + authored_coverage, 0.0001);
		vec4 road = vec4(1.0e20, 0.0, 0.0, 0.0);
		if (procedural_road_worldspace_blend_enabled) {
			road = procedural_road_field(world_position.xz);
		}
		float exterior_coverage = procedural_rolling_exterior_surface_enabled ?
			procedural_exterior_surface_coverage(
				world_position, surface_normal, road
			) : 1.0;

		vec4 generated_base_low = vec4(generated_low.x, 0.0, 0.0, 0.0);
		vec4 generated_base_high = vec4(0.0, generated_high.y, 0.0, 0.0);
		if (!procedural_ore_worldspace_blend_enabled) {
			generated_base_high.z = generated_high.z;
		}
		if (!procedural_road_worldspace_blend_enabled) {
			generated_base_high.w = generated_high.w;
		}
		vec4 generated_albedo = production_material_albedo_from_weights(
			generated_base_low,
			generated_base_high,
			world_position,
			surface_normal
		);
		float generated_roughness = production_material_roughness_from_weights(
			generated_base_low,
			generated_base_high,
			world_position,
			surface_normal
		);

		if (procedural_ore_worldspace_blend_enabled && generated_coverage > 0.0001) {
			float ore_host_coverage = clamp(
				(generated_low.x + generated_high.z) / generated_coverage,
				0.0,
				1.0
			);
			float ore_weight = procedural_ore_worldspace_weight(world_position) *
				ore_host_coverage;
			generated_albedo = mix(
				generated_albedo,
				production_albedo_color(8.0, world_position, surface_normal),
				ore_weight
			);
			generated_roughness = mix(
				generated_roughness,
				production_roughness_value(8.0, world_position, surface_normal),
				ore_weight
			);
		}

		vec4 surface_weights = vec4(
			generated_low.y,
			generated_low.z,
			generated_low.w,
			generated_high.x
		);
		float surface_coverage = surface_weight_sum(surface_weights);
		if (procedural_rolling_exterior_surface_enabled) {
			surface_weights = procedural_surface_biome_weights(world_position, road);
			surface_coverage = generated_coverage * exterior_coverage;
		}
		if (surface_coverage > 0.001) {
			surface_weights = normalized_surface_weights(surface_weights);
			float coverage = clamp(surface_coverage, 0.0, 1.0);
			generated_albedo = mix(
				generated_albedo,
				production_surface_albedo_color(surface_weights, world_position, surface_normal),
				coverage
			);
			generated_roughness = mix(
				generated_roughness,
				production_surface_roughness_value(surface_weights, world_position, surface_normal),
				coverage
			);
		}
		if (procedural_road_worldspace_blend_enabled) {
			float road_weight = procedural_road_worldspace_weight(world_position, road) *
				generated_coverage * exterior_coverage;
			if (road_weight > 0.001) {
				generated_albedo = mix(
					generated_albedo,
					production_albedo_color(10.0, world_position, surface_normal),
					road_weight
				);
				generated_roughness = mix(
					generated_roughness,
					production_roughness_value(10.0, world_position, surface_normal),
					road_weight
				);
			}
		}

		vec4 authored_albedo = production_material_albedo_from_weights(
			authored_low,
			authored_high,
			world_position,
			surface_normal
		);
		float authored_roughness = production_material_roughness_from_weights(
			authored_low,
			authored_high,
			world_position,
			surface_normal
		);
		float authored_mix = clamp(authored_coverage / total_coverage, 0.0, 1.0);
		vec4 albedo_texel = mix(generated_albedo, authored_albedo, authored_mix);
		float roughness_texel = mix(
			generated_roughness, authored_roughness, authored_mix
		);
		output_albedo = albedo_texel.rgb;
	}
	return output_albedo;
}

void main() {
	vec3 albedo = clamp(production_fragment_albedo(), vec3(0.0), vec3(1.0));
	vec3 unit_normal = normalize(world_normal);
	float light = 0.28 + 0.72 * abs(dot(
		unit_normal, normalize(vec3(0.35, 0.70, 0.62))
	));
	output_color = vec4(albedo * light, 1.0);
}
